GET http://localhost:3003/endereco/24240660
###
POST http://localhost:3003/user
Content-Type: application/json

{
    "cep": "24240660",
    "numero": "109",
    "complemento": "Casa perto de um colegio"
}