POST http://localhost:3003/signup
Content-Type: application/json

{
    "email": "Novo4@hotmail.com",
    "password": "123433555890",
    "name": "Novo4"
}

###

POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "Novo5@hotmail.com",
    "password": "123433555890"
}